[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.prod"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[[services]]
name = "frontend"
